name: motivacional
description: Una aplicaciÃ³n de frases motivacionales con autenticaciÃ³n Firebase.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # ðŸ”¥ Firebase
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.2.0

  # ðŸ’¬ Notificaciones y mensajes cortos
  fluttertoast: ^8.2.6

  # ðŸ’¡ Estado y utilidades
  provider: ^6.1.2

  # ðŸŽ¨ UI y efectos visuales
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  lottie: ^3.1.2

  # ðŸ“¤ Compartir frases
  share_plus: ^10.0.0

  # ðŸŒ InternacionalizaciÃ³n
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/lottie/fonts/Poppins-Regular.ttf
        - asset: assets/lottie/fonts/Poppins-Bold.ttf
          weight: 700
